### ISSUE TITLE
Why force compression?

### ISSUE THREAD

**Issue by shaunco** [rsanden/tumble#2]
You've made some really fantastic improvements over lumberjack, but why did you decide to force compression instead of leaving it as an option?

**Comment by rsanden-deca** [comment]
That's a great question.

Basically, assuming compression simplifies the program. I removed a lot of options to reduce the surface area for bugs. Definitely my fork is not something that should be merged upstream into Lumberjack proper because it would break other people's usage.

In the end, I chose to remove any options that I don't personally need. This eliminates situations where someone comes along and uses some option which I had retained but (surprise!) is mostly untested with my changes. I can think of few things more frustrating than digging into a server to debug a problem in production only to find that your logger failed the one job you hired it for.

This was really designed for a very specific use case where we want logs to archive for quite literally as long as possible, yet without accidentally filling the disk. Therefore, the total size must take into consideration the compressed log sizes. A lot of the logic for correct operation was added to handle potential race conditions during compression and rotation. So I really don't think this tool offers anything of value to someone who would actually use it without compression enabled.
